### ISSUE TITLE
'tar' is not recognized as an internal or external command, operable program, or batch file

### ISSUE THREAD

**Issue by Crakkerjakked** [llSourcell/tensorflow_speech_recognition_demo#21]
Como es what? It's throwing this error. 

'tar' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\site-packages\spyder\utils\site\sitecustomize.py", line 880, in runfile
    execfile(filename, namespace)
  File "C:\Python\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "C:/Users/Jackson Andrews/Irene.py", line 16, in <module>
    X, Y = next(batch)
  File "C:\Users\Jackson Andrews\speech_data.py", line 164, in mfcc_batch_generator
    files = os.listdir(path)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'data/spoken_numbers_pcm/'

**Comment by hazelwolf** [comment]
Resolved the issue by starting the command in GitBash Terminal.

**Comment by dany9988** [comment]
@bhomitb- Could you pls elaborate how to solve this on windows machine? Getting above exception while executing the code in pycharm IDE.

**Comment by andyy97** [comment]
I faced the same problem. Resolved it by copying pasting the extracted spoken_numbers_pcm folder in the data/ directory.
You may download spoken_numbers_pcm from the following link:
http://pannous.net/files/spoken_numbers_pcm.tar

**Comment by hcchengithub** [comment]
@dany9988 
on Windows 10, I simply manually unzip the ...\GitHub\tensorflow_speech_recognition_demo\data\spoken_numbers_pcm.tar 
to 
...\GitHub\tensorflow_speech_recognition_demo\data\spoken_numbers_pcm\
and it works fine then.
