### ISSUE TITLE
 from tensorflow.contrib.rnn.python.ops.core_rnn import static_rnn as _rnn, \ ImportError: No module named core_rnn

### ISSUE THREAD

**Issue by samimoftheworld** [llSourcell/tensorflow_speech_recognition_demo#9]
$ python demo.py 
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import tflearn
  File "/usr/local/lib/python2.7/dist-packages/tflearn/__init__.py", line 21, in <module>
    from .layers import normalization
  File "/usr/local/lib/python2.7/dist-packages/tflearn/layers/__init__.py", line 10, in <module>
    from .recurrent import lstm, gru, simple_rnn, bidirectional_rnn, \
  File "/usr/local/lib/python2.7/dist-packages/tflearn/layers/recurrent.py", line 8, in <module>
    from tensorflow.contrib.rnn.python.ops.core_rnn import static_rnn as _rnn, \
ImportError: No module named core_rnn

**Comment by spirovga** [comment]
You will should delete current Tensorflow version and install again. Just ignore requirements. On Ubuntu it looks like:
_**$sudo pip uninstall tensorflow
$sudo pip install tensorflow**_
Pip is Python module for easy install other modules (libraries)

Maybe the following helps you in other case:
_**-Change interpreter of current Project (either to 3.5 or 2.7)**_
